[package]
name = "wave_crafter"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = { version = "0.15", features = ["host-trait", "stream-trait", "device-trait"] } # For audio output
eframe = "0.20" # For GUI framework
egui = "0.20" # For GUI components
