[package]
name = "wave_crafter"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15"
eframe = "0.22"
egui = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hound = "3.4.0"
plotters = "0.3"
rustfft = "6.0"
