[package]
name = "wave_crafter"
version = "0.1.0"
edition = "2021"
description = "WaveCraft is a Rust-based audio synthesizer and digital audio workstation."
license = "MIT"
repository = "https://github.com/your-repo/wave.crafter"

[dependencies]
cpal = "0.15"
eframe = "0.22"
egui = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hound = "3.4.0"
plotters = "0.3"
rustfft = "6.0"

[package.metadata.bundle]
name = "Wave Crafter"
identifier = "com.example.wavecrafter"
icon = "assets/icon.png" # Ensure this file exists
