[package]
name = "wave_crafter"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15"
eframe = "0.20" # For GUI framework
egui = "0.20" # For GUI components
serde = { version = "1.0", features = ["derive"] } # For serialization
serde_json = "1.0" # For JSON handling
hound = "3.4.0"
